# Generated by Django 4.2.2 on 2023-06-26 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('relais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointrelais',
            name='created_at',
        ),
        migrations.AddField(
            model_name='pointrelais',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pointrelais',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pointrelais',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
