# Generated by Django 4.2.2 on 2023-06-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relais', '0005_alter_pointrelais_key_alter_pointrelais_relay_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrelais',
            name='key',
            field=models.CharField(default='USOENEW7HZ', max_length=10, unique=True),
        ),
    ]
