# Generated by Django 4.2.2 on 2023-06-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relais', '0007_alter_pointrelais_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrelais',
            name='key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
