# Generated by Django 4.2.2 on 2023-06-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relais', '0011_pointrelais_quartier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrelais',
            name='quartier',
            field=models.CharField(choices=[('Adidogomé', 'Adewui'), ('Avenou', 'Adewui'), ('Kagomé', 'Lomé 2')], max_length=300),
        ),
    ]
